// 指定使用 Protocol Buffers 第3版语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0--rc2
// source: food.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义一个请求消息结构
type FoodStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 定义一个字符串类型的字段name，字段编号为1
	// 字段编号用于在二进制编码中标识字段，不能重复
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodStreamRequest) Reset() {
	*x = FoodStreamRequest{}
	mi := &file_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStreamRequest) ProtoMessage() {}

func (x *FoodStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStreamRequest.ProtoReflect.Descriptor instead.
func (*FoodStreamRequest) Descriptor() ([]byte, []int) {
	return file_food_proto_rawDescGZIP(), []int{0}
}

func (x *FoodStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 定义一个响应消息结构
type FoodStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 定义一个字符串类型的字段msg，字段编号为1
	Msg           string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodStreamResponse) Reset() {
	*x = FoodStreamResponse{}
	mi := &file_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStreamResponse) ProtoMessage() {}

func (x *FoodStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStreamResponse.ProtoReflect.Descriptor instead.
func (*FoodStreamResponse) Descriptor() ([]byte, []int) {
	return file_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodStreamResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_food_proto protoreflect.FileDescriptor

const file_food_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"food.proto\"'\n" +
	"\x11FoodStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x12FoodStreamResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xb5\x01\n" +
	"\vFoodService\x124\n" +
	"\aSayName\x12\x12.FoodStreamRequest\x1a\x13.FoodStreamResponse0\x01\x125\n" +
	"\bPostName\x12\x12.FoodStreamRequest\x1a\x13.FoodStreamResponse(\x01\x129\n" +
	"\n" +
	"FullStream\x12\x12.FoodStreamRequest\x1a\x13.FoodStreamResponse(\x010\x01B\x05Z\x03/pbb\x06proto3"

var (
	file_food_proto_rawDescOnce sync.Once
	file_food_proto_rawDescData []byte
)

func file_food_proto_rawDescGZIP() []byte {
	file_food_proto_rawDescOnce.Do(func() {
		file_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_food_proto_rawDesc), len(file_food_proto_rawDesc)))
	})
	return file_food_proto_rawDescData
}

var file_food_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_food_proto_goTypes = []any{
	(*FoodStreamRequest)(nil),  // 0: FoodStreamRequest
	(*FoodStreamResponse)(nil), // 1: FoodStreamResponse
}
var file_food_proto_depIdxs = []int32{
	0, // 0: FoodService.SayName:input_type -> FoodStreamRequest
	0, // 1: FoodService.PostName:input_type -> FoodStreamRequest
	0, // 2: FoodService.FullStream:input_type -> FoodStreamRequest
	1, // 3: FoodService.SayName:output_type -> FoodStreamResponse
	1, // 4: FoodService.PostName:output_type -> FoodStreamResponse
	1, // 5: FoodService.FullStream:output_type -> FoodStreamResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_food_proto_init() }
func file_food_proto_init() {
	if File_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_food_proto_rawDesc), len(file_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_food_proto_goTypes,
		DependencyIndexes: file_food_proto_depIdxs,
		MessageInfos:      file_food_proto_msgTypes,
	}.Build()
	File_food_proto = out.File
	file_food_proto_goTypes = nil
	file_food_proto_depIdxs = nil
}
